### PR TITLE
#372 with comments fixed

### PR DESCRIPTION
**Pull request by Mathieu-Lala**
Fixed the comments for the PR #372.

### CODE REVIEW

**Comment by Keruspe** [comment]
This is now ok for me... but I think we need to consider this a breaking change. If people disable default features e.g. to use another TLS implementation, it will break their code on a minor update which is not acceptable.

Let's queue this for 3.0 which will probably happen once nom 8 and async fn in traits are stable

**Comment by Mathieu-Lala** [comment]
I think this change on a minor release won't bother the user too much, especially if a clear breaking changes section is added to the changelog.

**Comment by Keruspe** [comment]
Now that we're going to issue a 3.0 alpha, this can definitely go in!

Thinking back about this, I'd rather change the expect to return an error instead.

I'll probably do that some time next week unless you want to give it a shot

**Comment by Keruspe** [comment]
Also, could you please rebase to fix merge conflict?

**Pull request merged**
